### ISSUE TITLE
Lemonbeat command

### ISSUE THREAD

**Issue by FredBit90** [andrexp/gardena-local-control#1]
@andrexp 

Script to get the Commands from e.g. lawnrobot. Start the script with Python3 and send a command with the gardena app e.g. park_until

```
import time
from pynng import Pub0, Sub0

with Sub0(dial='ipc:///tmp/lemonbeatd-event.ipc', recv_timeout=20000) as sub0:
        sub0.subscribe("")
        print(sub0.recv())

```

The script prints following output:

```
b'[{"entity":{"device":"XXXX_DEVICE_ID_XXXX","path":"lemonbeat/0"},"metadata":{"sequence":152,"source":"lemonbeatd"},"op":"update","payload":{"action_paused_until_1":{"ts":1681851773,"vo":"+AcMHxYA"}}}]'
```

Copy the complete output to the following script and replace the "op":"update" with "op":"write":

```
import time
from pynng import Pub0, Sub0, Req0

with Req0(dial='ipc:///tmp/lemonbeatd-command.ipc') as req:
        req.send(b'[{"entity":{"device":"XXXX_DEVICE_ID_XXXX","path":"lemonbeat/0"},"metadata":{"sequence":152,"source":"lemonbeatd"},"op":"write","payload":{"action_paused_until_1":{"
        print(req.recv())

with Sub0(dial='ipc:///tmp/lemonbeatd-event.ipc', recv_timeout=5000) as sub0:
        sub0.subscribe("")
        print(sub0.recv())
```

If you start this script, the device will change the state to paused_until. You get the following output:

```
b'[{"entity":{"device":"XXXX_DEVICE_ID_XXXX","path":"lemonbeat/0"},"metadata":{"sequence":203,"source":"lemonbeatd"},"payload":null,"success":true}]'
b'[{"entity":{"device":"XXXX_DEVICE_ID_XXXX","path":"lemonbeat/0"},"metadata":{"sequence":156,"source":"lemonbeatd"},"op":"update","payload":{"action_paused_until_1":{"ts":1681852110,"vo":"+AcMHxYA"}}}]'
```

I think we only need to send all commands we will support with the Gardena app and receive the message with the first getCommand.py script. 
This is the first thing we must do, to collect all commands to analyze.

**Comment by andrexp** [comment]
Good work!

As you already suggested the commands are coded in Base64. E.g. sending a telegram through changing settings you will get the commands we already have reverse engineered in [https://github.com/andrexp/gardena-local-control/blob/main/control_telegram](control_telegram)

I will add a file to collect all of those commands we will get back from subscribe to the event.ipc

**Comment by FredBit90** [comment]
A file to collect all of the commands is a good idea. Can you start with collecting the commands to the file?
I will create a template for a service based on python to communicate with our own mqtt broker.  Then we can work parralel at the script.
